### ISSUE TITLE
seperate contact request and read contact request

### ISSUE THREAD

**Issue by RyanCather** [Lake-Tuggeranong-College/CyberCity#538]
I made an extra column in the database to make the two pages separable by a button that moves the contact requests from the 'contact request' page to the 'read contact requests' page to separate what ones have been dealt with and solved.

for client: no complications occurred whilst separating the two different contact request pages. asking for feedback from client @RyanCather .

**Comment by RyanCather** [comment]
Approved.

Good solution to mark contacts as completed.

**Comment by yeahrandom** [comment]
Much appreciated for confirmation.
